# Logistic Regression

For 1 training example

\begin{align*}
z = w^Tx + b \\
\hat{y} = \sigma(z) = \frac{1}{1 + e^{-z}} \\
L(\hat{y}, y) = -(y\log\hat{y} + (1 - y)\log(1 - \hat{y}))
\end{align*}

## Loss function: Multiclass log loss

\begin{align*}
L(\hat{y}, y) = -(y\log\hat{y} + (1 - y)\log(1 - \hat{y}))
\end{align*}

### Case 1

\begin{align*}
y = 1 \\
\hat{y} = 0.99
\end{align*}


\begin{align*}
L(\hat{y}, y) = -(1\log{0.99} + (1 - 1)\log(1 - 0.99)) \\
L(\hat{y}, y) = -1\log{0.99} \\
 = 0.004364
\end{align*}

### Case 2

\begin{align*}
y = 1 \\
\hat{y} = 0.01
\end{align*}


\begin{align*}
L(\hat{y}, y) = -(1\log{0.01} + (1 - 1)\log(1 - 0.01)) \\
L(\hat{y}, y) = -1\log{0.01} \\
 = 2
\end{align*}

When $y = 1$, $L(\hat{y}, y) = -\log\hat{y}$, we need $\hat{y}$ to be as large as possible so that 

### Case 3

\begin{align*}
y = 0 \\
\hat{y} = 0.99
\end{align*}


\begin{align*}
L(\hat{y}, y) = -(0\log{0.99} + (1 - 0)\log(1 - 0.99)) \\
L(\hat{y}, y) = -1\log{0.01} \\
 = 2
\end{align*}

### Case 4

\begin{align*}
y = 0 \\
\hat{y} = 0.01
\end{align*}


\begin{align*}
L(\hat{y}, y) = -(0\log{0.01} + (1 - 0)\log(1 - 0.01)) \\
L(\hat{y}, y) = -1\log{0.99} \\
 = 0.004364
\end{align*}

When $y = 0$, $L(\hat{y}, y) = -\log(1 - \hat{y})$, we need $\hat{y}$ to be as small as possible

For $m$ training examples, add them up and average them. 

\begin{align*}
J(\hat{y}, y) = -\frac{1}{m}\sum_{i = 0}^{m - 1}(y^{(i)}\log\hat{y}^{(i)} + (1 - y^{(i)})\log(1 - \hat{y}^{(i)})) 
\end{align*}
Where data is indexed from $0$ as in most programming languages

Recall that, for a single training example

\begin{align*}
z = w^Tx + b
\end{align*}

If we assume that for this one training examples, there are $2$ features $x_1$ and $x_2$, the reason for assuming $2$ features is so that, we can extend this example to multiple features. The goal is to explain how gradient descent update takes place.

\begin{align*}
z = w_1x_1 + w_2x_2 + b \\
\hat{y} = \sigma(z) = \frac{1}{1 + e^{-z}} \\
L(\hat{y}, y) = -(y\log\hat{y} + (1 - y)\log(1 - \hat{y}))
\end{align*}

For notational convenience, Let $L(\hat{y}, y)$ be represented by $L$

## Gradient Descent Update Overview

In gradient descent, we perform the following update. 

\begin{align*}
w_1 = w_1 - \alpha\frac{\partial L}{\partial w_1} \\
w_2 = w_2 - \alpha\frac{\partial L}{\partial w_2} \\
b = b -  \alpha\frac{\partial L}{\partial b} 
\end{align*}

This would represent ONE iteration of gradient descent

Now that we have an updated $w_1$, $w_2$, we refit them in our equation

\begin{align*}
z = w_1x_1 + w_2x_2 + b \\
\hat{y} = \sigma(z) = \frac{1}{1 + e^{-z}} \\
L(\hat{y}, y) = -(y\log\hat{y} + (1 - y)\log(1 - \hat{y}))
\end{align*}

we then, do the performance update

\begin{align*}
w_1 = w_1 - \alpha\frac{\partial L}{\partial w_1} \\
w_2 = w_2 - \alpha\frac{\partial L}{\partial w_2} \\
b = b -  \alpha\frac{\partial L}{\partial b} 
\end{align*}

for many iterations and finally end up with $w_1$, $w_2$ and $b$ which we would go on to use for our test set

There are many ways we can think about how to perform this gradient descent update. Rewriting our equation

\begin{align*}
z = w_1x_1 + w_2x_2 + b \\
\hat{y} = \sigma(z) = \frac{1}{1 + e^{-z}} \\
L = -(y\log\hat{y} + (1 - y)\log(1 - \hat{y})) \\
L = -(y\log\sigma(z) + (1 - y)\log(1 - \sigma(z))) \\
L = -\left(y\log\frac{1}{1 + e^{-z}} + (1 - y)\log\left(1 - \frac{1}{1 + e^{-z}}\right)\right) \\
L = -\left(y\log\frac{1}{1 + e^{-(w_1x_1 + w_2x_2 + b)}} + (1 - y)\log\left(1 - \frac{1}{1 + e^{-(w_1x_1 + w_2x_2 + b)}}\right)\right) \\
\end{align*}

and then take it from here. Or you could simply use the chain rule! But first, let's get a small intuition of the chain rule

In a race, Usain Bolt is travelling twice as fast as a train which is going 3 times as fast as a horse. How do I represent Usain Bolt's speed with respect to the horse?

\begin{align*}
\frac{\partial \text{Bolt}}{\partial\text{Horse}}= \frac{\partial\text{Bolt}}{\partial\text{Train}} \cdot \frac{\partial\text{Train}}{\partial\text{Horse}} = 2\cdot 3 = 6
\end{align*}

\begin{align*}
z = w_1x_1 + w_2x_2 + b \\
\hat{y} = \sigma(z) = \frac{1}{1 + e^{-z}} \\
L = -(y\log\hat{y} + (1 - y)\log(1 - \hat{y}))
\end{align*}

Similarly, to find, $\frac{\partial L}{\partial w_1}$, we need to know how $L$ moves with respect to $\hat{y}$ whose movement is affected by how $z$ moves, which in turn is affected by $w_1$, $w_2$ and $b$ 

\begin{align*}
\frac{\partial L}{\partial w_1} = \frac{\partial L}{\partial \hat{y}} \times \frac{\partial \hat{y}}{\partial z} \times \frac{\partial z}{\partial w_1}
\end{align*}

\begin{align*}
\frac{\partial L}{\partial \hat{y}} = -\frac{y}{\hat{y}} + \frac{1 - y}{1 - \hat{y}} \\
\frac{\partial \hat{y}}{\partial z} = \frac{\partial \sigma (z)}{\partial z} = \sigma (z)\cdot (1-\sigma(z)) = \hat{y}\cdot(1 - \hat{y}) \\
\frac{\partial z}{\partial w_1} = x_1
\end{align*}

\begin{align*}
\frac{\partial L}{\partial w_1} = x_1\cdot(\hat{y} - y)
\end{align*}

I think you can see a pattern emerging here

\begin{align*}
\frac{\partial L}{\partial w_2} = x_2\cdot(\hat{y} - y)
\end{align*}

and finally

\begin{align*}
\frac{\partial L}{\partial b} = \hat{y} - y
\end{align*}

### Gradient Descent Update for a single iteration

Initialize once

$J = 0$, $\frac{\partial L}{\partial w_1} = 0$, $\frac{\partial L}{\partial w_2} = 0$, $\frac{\partial L}{\partial b} = 0$, 

For $m$ training examples, we would do the following for 1 iteration of Gradient Descent

for $i = 0$ to $i = m$:

\begin{align*}
z^{(i)} = w^Tx^{(i)} + b \\
\hat{y}^{(i)} = \sigma(z^{(i)}) \\
J = -(y^{(i)}\log\hat{y}^{(i)} + (1 - y^{(i)})\log(1 - \hat{y}^{(i)})) \\
 \frac{\partial L}{\partial z}^{(i)} = \hat{y}^{(i)} - y^{(i)} \\
 \frac{\partial L}{\partial w_1} =  \frac{\partial L}{\partial w_1} + x_1^{(i)}(\hat{y}^{(i)} - y^{(i)}) \\
 \frac{\partial L}{\partial w_2} =  \frac{\partial L}{\partial w_2} + x_2^{(i)}(\hat{y}^{(i)} - y^{(i)}) \\
 \frac{\partial L}{\partial b} =  \frac{\partial L}{\partial b} + (\hat{y}^{(i)} - y^{(i)})
\end{align*}

$J = \frac{J}{m}$, $\frac{\partial L}{\partial w_1} = \frac{\frac{\partial L}{\partial w_1}}{m}$, $\frac{\partial L}{\partial w_2} = \frac{\frac{\partial L}{\partial w_2}}{m}$, $\frac{\partial L}{\partial b} = \frac{\frac{\partial L}{\partial b}}{m}$

After finding $\frac{\partial L}{\partial w_1}$, $\frac{\partial L}{\partial w_2}$ and $\frac{\partial L}{\partial b}$  make the update

\begin{align*}
w_1 = w_1 - \alpha\frac{\partial L}{\partial w_1} \\
w_2 = w_2 - \alpha\frac{\partial L}{\partial w_2} \\
b = b -  \alpha\frac{\partial L}{\partial b} 
\end{align*}

## Non-Vectorized Logistic Regression for Binary Classification

In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame([[50, 60, 80, 90, 21], [54, 70, 90, 99, 22], [0, 1, 1, 1, 0]]).T
df.columns = ['Attendance (x1)', 'Math score (x2)', 'True label (y)']
print(df)

   Attendance (x1)  Math score (x2)  True label (y)
0               50               54               0
1               60               70               1
2               80               90               1
3               90               99               1
4               21               22               0


In [210]:
w1 = 0.0001 #Initial values
w2 = 0.0002 #Initial values
b = 0 #Initial values

def cost(y, yhat):
    
    return -((y*np.log(yhat)) + (1 - y)*np.log(1 - yhat))

def sigmoid(x):
    return 1/(1 + np.exp(-(x)))

for iter_num in range(0, 3):
    
    
    J = 0
    dw1 = 0
    dw2 = 0
    db = 0


    for row in df.index:

        x1 = df.loc[row]['Attendance (x1)']
        x2 = df.loc[row]['Math score (x2)']
        y = df.loc[row]['True label (y)']
        z = w1*x1 + w2*x2 + b
        #print("z for training example no. {} is {}".format(i, z))
        yhat = sigmoid(z)
        
        #print("yhat (Prediction) for training example {} is {}".format(i, yhat))
        #print("y (True label) for training example {} is {}".format(i, y))
        J = J + cost(y, yhat)
        #print("J (Cost) for training example {} is {}".format(i, cost(y, yhat)))

        dz = (yhat - y)
        
        
        dw1 = dw1 + x1*(yhat - y)
        dw2 = dw2 + x2*(yhat - y)
        db = db + dz
    

    dw1 =  dw1/len(df)
    dw2 =  dw2/len(df)
    db = db/len(df)
    
    J = J/len(df)
    print("Average cost after {} iteration is {}".format(iter_num, J))
    w1 = w1 - 0.001*dw1
    w2 = w2 - 0.001*dw2
    b = b - 0.001*db


Average cost after 0 iteration is 0.6879521123839162
Average cost after 1 iteration is 0.6480712626560493
Average cost after 2 iteration is 0.5600657119963963


In [211]:
print(w1, w2)

0.007117425235320776 0.009698896322646137


## Vectorized Logistic Regression for Binary Classification

1. Create a matrix out of our training data, and out of our labels. The training data that has the features and the samples must be set in such a way that each column is a training example, as opposed to how normally we assume by default that each row is a training example

In [218]:
data = df[['Attendance (x1)', 'Math score (x2)']]
data = data.T

data = np.array(data)
print(data)
print(data.shape)


[[50 60 80 90 21]
 [54 70 90 99 22]]
(2, 5)


2. Your label `(y)` must be a row vector

In [219]:
y = df[['True label (y)']]
y = np.array(y.T)
print(y.shape)
print(y)



(1, 5)
[[0 1 1 1 0]]


3. Your weights `(w)` should be matrix of dimension `(num_features, 1)`. We know that `b` and `db` and `J` are scalars.

In [220]:
def initialize():

    w = np.array([0.0001, 0.0002])
    w = w.reshape((w.shape[0], 1))
    
    b = 0
    
    
    return w, b

def cost(y, yhat):
    
    return -((y*np.log(yhat)) + (1 - y)*np.log(1 - yhat))

def sigmoid(x):
    
    return 1/(1 + np.exp(-(x)))

def update_param(w, b, dw, db):
    
    w = w - 0.001*dw
    b = b - 0.001*db
    
    return w, b

In [221]:
def forwardprop(w, b, num_iter, y, data, m):
    
    for iter_num in range(0, num_iter):
        
        z = np.dot(w.T, data) + b

        yhat = sigmoid(z)

        J = np.mean(cost(y, yhat))
        print("Cost: ", J)

        dz = (yhat - y)

        dw = np.dot(data, dz.T)/m
        db = np.mean(dz)

        w, b = update_param(w, b, dw, db)
        
    return w, b
    

In [222]:
w, b = initialize()
w, b = forwardprop(w, b, 3, y, data, 5)

Cost:  0.6879521123839162
Cost:  0.6480712626560493
Cost:  0.5600657119963963


In [223]:
w

array([[0.00711743],
       [0.0096989 ]])

In [224]:
b

-0.00030145999968170397

## Trivia

### Choice of learning rate

In order for Gradient Descent to work you must choose the learning rate wisely. The learning rate $\alpha$  determines how rapidly we update the parameters. If the learning rate is too large we may "overshoot" the optimal value. Similarly, if it is too small we will need too many iterations to converge to the best values. That's why it is crucial to use a well-tuned learning rate.

### Need for random initialization of weights

In Logistic Regression, it is okay to initialize weights to zero. But for a shallow neural network or a deep neural network, the hidden units become completely symmetric and compute the exact some function (can be proven by induction), the hidden units are symmetric even after many iterations

# Neural Networks (Shallow)

# SVD